import RPi.GPIO as GPIO
import os
import time

#SETUP
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

#SETUP BUTTONS
#DAYMAN
GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)
#NIGHTMAN
GPIO.setup(27, GPIO.IN, pull_up_down=GPIO.PUD_UP)
#STOP&SAVE
GPIO.setup(22, GPIO.IN, pull_up_down=GPIO.PUD_UP)
#SHUTDOWN
GPIO.setup(18, GPIO.IN, pull_up_down=GPIO.PUD_UP)
#EMERGENCY DELETE
GPIO.setup(23, GPIO.IN, pull_up_down=GPIO.PUD_UP)

#SETUP LEDS
#RED
GPIO.setup(2,GPIO.OUT)
#GREEN1
GPIO.setup(3,GPIO.OUT)
#GREEN2
GPIO.setup(4,GPIO.OUT)
#ACTIVATE LEDS
GPIO.output(2,GPIO.HIGH)
GPIO.output(3,GPIO.LOW)
GPIO.output(4,GPIO.LOW)

while True:
	buttonLL = GPIO.input(17)
	buttonML = GPIO.input(27)
	buttonMR = GPIO.input(22)
	buttonRR = GPIO.input(18)
	buttonER = GPIO.input(23)
	if buttonLL == False:
		os.system("python /home/pi/cam/dayman.py &")
		GPIO.output(2,GPIO.LOW)
		GPIO.output(3,GPIO.HIGH)
		GPIO.output(3,GPIO.LOW)
		time.sleep(0.3)
		GPIO.output(3,GPIO.HIGH)
		time.sleep(0.3)
		GPIO.output(3,GPIO.LOW)
		time.sleep(0.3)
		GPIO.output(3,GPIO.HIGH)
		time.sleep(1)
	if buttonML == False:
		os.system("python /home/pi/cam/nightman.py &")
		GPIO.output(2,GPIO.LOW)
		GPIO.output(3,GPIO.HIGH)
		GPIO.output(4,GPIO.HIGH)
                GPIO.output(3,GPIO.LOW)
		GPIO.output(4,GPIO.LOW)
                time.sleep(0.3)
                GPIO.output(3,GPIO.HIGH)
                GPIO.output(4,GPIO.HIGH)
		time.sleep(0.3)
		GPIO.output(3,GPIO.LOW)
		GPIO.output(4,GPIO.LOW)
                time.sleep(0.3)
                GPIO.output(3,GPIO.HIGH)
		GPIO.output(4,GPIO.HIGH)
		time.sleep(1)
        if buttonMR == False:
		os.system("sudo pkill -9 -f raspivid")
		os.system("sudo pkill -9 -f dayman.py")
		os.system("sudo pkill -9 -f nightman.py")
		GPIO.output(3,GPIO.LOW)
		GPIO.output(4,GPIO.LOW)
		GPIO.output(2,GPIO.HIGH)
		time.sleep(0.2)
		GPIO.output(2,GPIO.LOW)
		time.sleep(0.2)
		GPIO.output(2,GPIO.HIGH)
		time.sleep(0.2)
		GPIO.output(2,GPIO.LOW)
		time.sleep(0.2)
		GPIO.output(2,GPIO.HIGH)
                time.sleep(1)
        if buttonRR == False:
		os.system("sudo shutdown -h now")
		GPIO.output(3,GPIO.LOW)
                GPIO.output(4,GPIO.LOW)
                GPIO.output(2,GPIO.HIGH)
		time.sleep(0.2)
		GPIO.output(2,GPIO.LOW)
		time.sleep(0.2)
		GPIO.output(2,GPIO.HIGH)
		time.sleep(0.2)
		GPIO.output(2,GPIO.LOW)
		time.sleep(0.2)
		GPIO.output(2,GPIO.HIGH)
		time.sleep(0.2)
		GPIO.output(2,GPIO.LOW)
		time.sleep(0.2)
		GPIO.output(2,GPIO.HIGH)
		time.sleep(0.2)
		GPIO.output(2,GPIO.LOW)
		time.sleep(0.2)
		GPIO.output(2,GPIO.HIGH)
		time.sleep(0.5)

	if buttonER == False:
                os.system("sudo rm /mnt/DASH/dayman/*")
		time.sleep(0.1)
		os.system("sudo rm /mnt/DASH/nightman/*")
                GPIO.output(3,GPIO.LOW)
                GPIO.output(4,GPIO.LOW)
                GPIO.output(2,GPIO.HIGH)
                time.sleep(0.15)
                GPIO.output(2,GPIO.LOW)
		GPIO.output(3,GPIO.HIGH)
		time.sleep(0.15)
		GPIO.output(3,GPIO.LOW)
		GPIO.output(4,GPIO.HIGH)
		time.sleep(0.15)
                GPIO.output(4,GPIO.LOW)
		GPIO.output(2,GPIO.HIGH)
                time.sleep(0.15)
                GPIO.output(2,GPIO.LOW)
                GPIO.output(3,GPIO.HIGH)
                time.sleep(0.15)
                GPIO.output(3,GPIO.LOW)
                GPIO.output(4,GPIO.HIGH)
                time.sleep(0.15)
                GPIO.output(4,GPIO.LOW)
                GPIO.output(2,GPIO.HIGH)
                time.sleep(0.15)
		GPIO.output(2,GPIO.LOW)
                GPIO.output(3,GPIO.HIGH)
                time.sleep(0.15)
                GPIO.output(3,GPIO.LOW)
                GPIO.output(4,GPIO.HIGH)
                time.sleep(0.15)
                GPIO.output(4,GPIO.LOW)
                GPIO.output(2,GPIO.HIGH)
                time.sleep(1)
